// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PIA_MAD.Modelos;

#nullable disable

namespace PIA_MAD.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250512064419_VistaHotelFix")]
    partial class VistaHotelFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PIA_MAD.Clases.HistorialClienteDTO", b =>
                {
                    b.Property<decimal>("Anticipo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CantidadPersonas")
                        .HasColumnType("int");

                    b.Property<string>("CiudadHotel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CodigoReservacion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCheckOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hotel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontoDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoHospedaje")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoServicios")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumHabitacion")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoHabitacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalFactura")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("PIA_MAD.Clases.HotelUbicacionDTO", b =>
                {
                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("domicilio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("VistaHotelesUbicacion", (string)null);
                });

            modelBuilder.Entity("PIA_MAD.Clases.UsuarioVistaDTO", b =>
                {
                    b.Property<string>("AM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaNa")
                        .HasColumnType("datetime2");

                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("VistaUsuariosSimplificada", (string)null);
                });

            modelBuilder.Entity("PIA_MAD.Clases.VistaHabitacionesHotelesDTO", b =>
                {
                    b.Property<int>("HabitacionId")
                        .HasColumnType("int");

                    b.Property<string>("NivelHabitacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreHotel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("VistaHabitacionesHoteles", (string)null);
                });

            modelBuilder.Entity("PIA_MAD.Modelos.Administrador", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("AM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nomina")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaNa")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.Cancelaciones", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("AdministradorId")
                        .HasColumnType("int");

                    b.Property<decimal>("AnticipoADevolver")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CantPersonas")
                        .HasColumnType("int");

                    b.Property<bool>("CheckInRealizado")
                        .HasColumnType("bit");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<Guid>("CodigoReserva")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCancelacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEnt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSal")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("TipoCancelacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("AdministradorId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("HotelId");

                    b.ToTable("Cancelaciones");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.CheckOut", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("Anticipo")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CantPersonas")
                        .HasColumnType("int");

                    b.Property<decimal>("CantidadDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("CheckInRealizado")
                        .HasColumnType("bit");

                    b.Property<bool>("CheckOUtRealizado")
                        .HasColumnType("bit");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<Guid>("CodigoReserva")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEntReserva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSalReal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSalReserva")
                        .HasColumnType("datetime2");

                    b.Property<int>("FolioFactura")
                        .HasColumnType("int");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OperativoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PorcentajeDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RutaPdfFactura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerieFactura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("HotelId");

                    b.HasIndex("OperativoId");

                    b.ToTable("CheckOut");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.CheckOutServicioAdicional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CheckOutId")
                        .HasColumnType("int");

                    b.Property<int>("ServicioAdicionalHotelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CheckOutId");

                    b.HasIndex("ServicioAdicionalHotelId");

                    b.ToTable("CheckOutServiciosAdicionales");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.HabitacionCancelacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CancelacionId")
                        .HasColumnType("int");

                    b.Property<int?>("Cancelacionesid")
                        .HasColumnType("int");

                    b.Property<int>("CantidadPersonas")
                        .HasColumnType("int");

                    b.Property<int>("HabitacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CancelacionId");

                    b.HasIndex("Cancelacionesid");

                    b.HasIndex("HabitacionId");

                    b.ToTable("HabitacionCancelacion");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.HabitacionCheckout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadPersonas")
                        .HasColumnType("int");

                    b.Property<int>("CheckOutId")
                        .HasColumnType("int");

                    b.Property<int>("HabitacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CheckOutId");

                    b.HasIndex("HabitacionId");

                    b.ToTable("HabitacionCheckout");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.HabitacionReservada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadPersonas")
                        .HasColumnType("int");

                    b.Property<int>("HabitacionId")
                        .HasColumnType("int");

                    b.Property<int>("ReservacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HabitacionId");

                    b.HasIndex("ReservacionId");

                    b.ToTable("HabitacionReservada");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.Habitaciones", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Amenidades")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<int>("CreadorAdministradorId")
                        .HasColumnType("int");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int?>("ModificadorAdministradorId")
                        .HasColumnType("int");

                    b.Property<int>("NoCamas")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioNoche")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Vista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caracteristicas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nivelHab")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoCama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("CreadorAdministradorId");

                    b.HasIndex("HotelId");

                    b.HasIndex("ModificadorAdministradorId");

                    b.ToTable("Habitaciones");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.HotelListado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("HotelesPorUbicacion");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.Hoteles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("CantPiscina")
                        .HasColumnType("int");

                    b.Property<int>("CreadorAdministradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FrentePlaya")
                        .HasColumnType("bit");

                    b.Property<int?>("ModificadorAdministradorId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pisos")
                        .HasColumnType("int");

                    b.Property<bool>("SalonEv")
                        .HasColumnType("bit");

                    b.Property<bool>("ZonaTur")
                        .HasColumnType("bit");

                    b.Property<string>("amenidades")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cantHab")
                        .HasColumnType("int");

                    b.Property<string>("caracteristicas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("domicilio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("CreadorAdministradorId");

                    b.HasIndex("ModificadorAdministradorId");

                    b.ToTable("Hoteles");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.Operativos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("AM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreadorAdministradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModificadorAdministradorId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nomina")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaNa")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("CreadorAdministradorId");

                    b.HasIndex("ModificadorAdministradorId");

                    b.ToTable("Operativos");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.RegistroContra", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("AdministradorId")
                        .HasColumnType("int");

                    b.Property<string>("ContraPasada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OperativoId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("AdministradorId");

                    b.HasIndex("OperativoId");

                    b.ToTable("RegistroContra");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.ReporteOcupacion", b =>
                {
                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("Mes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NochesOcupadas")
                        .HasColumnType("int");

                    b.Property<string>("NombreHotel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Personas")
                        .HasColumnType("int");

                    b.Property<string>("TipoHabitacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("PIA_MAD.Modelos.ReporteVentas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("AdministradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaGen")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PagosT")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("AdministradorId");

                    b.ToTable("ReporteVentas");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.Reservacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("Anticipo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CantPersonas")
                        .HasColumnType("int");

                    b.Property<bool>("CheckInRealizado")
                        .HasColumnType("bit");

                    b.Property<bool>("CheckOUtRealizado")
                        .HasColumnType("bit");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<Guid>("CodigoReserva")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEnt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSal")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("OperativoId")
                        .HasColumnType("int");

                    b.Property<int?>("ReporteVentasid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("HotelId");

                    b.HasIndex("OperativoId");

                    b.HasIndex("ReporteVentasid");

                    b.ToTable("Reservaciones");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.ServicioAdicionalHotel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("HotelId");

                    b.ToTable("ServiciosAdicionalesHotel");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("AM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cfdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigopostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreadorAdministradorId")
                        .HasColumnType("int");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaModifacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModificadorAdministradorId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegimenFiscal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaNa")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("CreadorAdministradorId");

                    b.HasIndex("ModificadorAdministradorId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.VentaAnticipoResultado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<decimal>("Anticipo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CantPersonas")
                        .HasColumnType("int");

                    b.Property<decimal>("CantidadDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("Mes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreHotel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ServiciosAdicionales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VentasYAnticiposView");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.Cancelaciones", b =>
                {
                    b.HasOne("PIA_MAD.Modelos.Administrador", "Administrador")
                        .WithMany()
                        .HasForeignKey("AdministradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PIA_MAD.Modelos.Usuario", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PIA_MAD.Modelos.Hoteles", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrador");

                    b.Navigation("Cliente");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.CheckOut", b =>
                {
                    b.HasOne("PIA_MAD.Modelos.Usuario", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PIA_MAD.Modelos.Hoteles", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PIA_MAD.Modelos.Operativos", "Operativo")
                        .WithMany()
                        .HasForeignKey("OperativoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Hotel");

                    b.Navigation("Operativo");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.CheckOutServicioAdicional", b =>
                {
                    b.HasOne("PIA_MAD.Modelos.CheckOut", "CheckOut")
                        .WithMany("ServiciosAdicionales")
                        .HasForeignKey("CheckOutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PIA_MAD.Modelos.ServicioAdicionalHotel", "ServicioAdicionalHotel")
                        .WithMany()
                        .HasForeignKey("ServicioAdicionalHotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CheckOut");

                    b.Navigation("ServicioAdicionalHotel");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.HabitacionCancelacion", b =>
                {
                    b.HasOne("PIA_MAD.Modelos.Cancelaciones", "Cancelacion")
                        .WithMany()
                        .HasForeignKey("CancelacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PIA_MAD.Modelos.Cancelaciones", null)
                        .WithMany("HabitacionesCanceladas")
                        .HasForeignKey("Cancelacionesid");

                    b.HasOne("PIA_MAD.Modelos.Habitaciones", "Habitacion")
                        .WithMany()
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cancelacion");

                    b.Navigation("Habitacion");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.HabitacionCheckout", b =>
                {
                    b.HasOne("PIA_MAD.Modelos.CheckOut", "CheckOut")
                        .WithMany("HabitacionCheckout")
                        .HasForeignKey("CheckOutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PIA_MAD.Modelos.Habitaciones", "Habitacion")
                        .WithMany()
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CheckOut");

                    b.Navigation("Habitacion");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.HabitacionReservada", b =>
                {
                    b.HasOne("PIA_MAD.Modelos.Habitaciones", "Habitacion")
                        .WithMany()
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PIA_MAD.Modelos.Reservacion", "Reservacion")
                        .WithMany("HabitacionReservada")
                        .HasForeignKey("ReservacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habitacion");

                    b.Navigation("Reservacion");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.Habitaciones", b =>
                {
                    b.HasOne("PIA_MAD.Modelos.Administrador", "Creador")
                        .WithMany()
                        .HasForeignKey("CreadorAdministradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PIA_MAD.Modelos.Hoteles", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PIA_MAD.Modelos.Administrador", "Modificador")
                        .WithMany()
                        .HasForeignKey("ModificadorAdministradorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creador");

                    b.Navigation("Hotel");

                    b.Navigation("Modificador");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.Hoteles", b =>
                {
                    b.HasOne("PIA_MAD.Modelos.Administrador", "Creador")
                        .WithMany()
                        .HasForeignKey("CreadorAdministradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PIA_MAD.Modelos.Administrador", "Modificador")
                        .WithMany()
                        .HasForeignKey("ModificadorAdministradorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creador");

                    b.Navigation("Modificador");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.Operativos", b =>
                {
                    b.HasOne("PIA_MAD.Modelos.Administrador", "Creador")
                        .WithMany()
                        .HasForeignKey("CreadorAdministradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PIA_MAD.Modelos.Administrador", "Modificador")
                        .WithMany()
                        .HasForeignKey("ModificadorAdministradorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creador");

                    b.Navigation("Modificador");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.RegistroContra", b =>
                {
                    b.HasOne("PIA_MAD.Modelos.Administrador", "Administrador")
                        .WithMany()
                        .HasForeignKey("AdministradorId");

                    b.HasOne("PIA_MAD.Modelos.Operativos", "Operativo")
                        .WithMany()
                        .HasForeignKey("OperativoId");

                    b.Navigation("Administrador");

                    b.Navigation("Operativo");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.ReporteVentas", b =>
                {
                    b.HasOne("PIA_MAD.Modelos.Administrador", "Administrador")
                        .WithMany()
                        .HasForeignKey("AdministradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrador");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.Reservacion", b =>
                {
                    b.HasOne("PIA_MAD.Modelos.Usuario", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PIA_MAD.Modelos.Hoteles", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PIA_MAD.Modelos.Operativos", "Operativo")
                        .WithMany()
                        .HasForeignKey("OperativoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PIA_MAD.Modelos.ReporteVentas", null)
                        .WithMany("reservaciones")
                        .HasForeignKey("ReporteVentasid");

                    b.Navigation("Cliente");

                    b.Navigation("Hotel");

                    b.Navigation("Operativo");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.ServicioAdicionalHotel", b =>
                {
                    b.HasOne("PIA_MAD.Modelos.Hoteles", "Hotel")
                        .WithMany("ServiciosAdicionales")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.Usuario", b =>
                {
                    b.HasOne("PIA_MAD.Modelos.Administrador", "Creador")
                        .WithMany()
                        .HasForeignKey("CreadorAdministradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PIA_MAD.Modelos.Administrador", "Modificador")
                        .WithMany()
                        .HasForeignKey("ModificadorAdministradorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creador");

                    b.Navigation("Modificador");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.Cancelaciones", b =>
                {
                    b.Navigation("HabitacionesCanceladas");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.CheckOut", b =>
                {
                    b.Navigation("HabitacionCheckout");

                    b.Navigation("ServiciosAdicionales");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.Hoteles", b =>
                {
                    b.Navigation("ServiciosAdicionales");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.ReporteVentas", b =>
                {
                    b.Navigation("reservaciones");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.Reservacion", b =>
                {
                    b.Navigation("HabitacionReservada");
                });
#pragma warning restore 612, 618
        }
    }
}
