// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PIA_MAD.Modelos;

#nullable disable

namespace PIA_MAD.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250422060222_FixCascadeError")]
    partial class FixCascadeError
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PIA_MAD.Modelos.Administrador", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("AM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nomina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaNa")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.HabitacionReservada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HabitacionId")
                        .HasColumnType("int");

                    b.Property<int>("ReservacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HabitacionId");

                    b.HasIndex("ReservacionId");

                    b.ToTable("HabitacionReservada");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.Habitaciones", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Amenidades")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("NoCamas")
                        .HasColumnType("int");

                    b.Property<int>("PrecioNoche")
                        .HasColumnType("int");

                    b.Property<string>("Vista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caracteristicas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechNaHab")
                        .HasColumnType("datetime2");

                    b.Property<string>("nivelHab")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoCama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("HotelId");

                    b.ToTable("Habitaciones");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.Hoteles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("CantPiscina")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechNaH")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FrentePlaya")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pisos")
                        .HasColumnType("int");

                    b.Property<bool>("SalonEv")
                        .HasColumnType("bit");

                    b.Property<bool>("ZonaTur")
                        .HasColumnType("bit");

                    b.Property<string>("amenidades")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cantHab")
                        .HasColumnType("int");

                    b.Property<string>("caracteristicas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("domicilio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("serviciosAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Hoteles");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.Operativos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("AM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nomina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaNa")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Operativos");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.RegistroContra", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("ContraPasada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("RegistroContra");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.ReporteVentas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("FechaGen")
                        .HasColumnType("datetime2");

                    b.Property<int>("PagosT")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("ReporteVentas");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.Reservacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("Anticipo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CantPersonas")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<Guid>("CodigoReserva")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaEnt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSal")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int?>("ReporteVentasid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("HotelId");

                    b.HasIndex("ReporteVentasid");

                    b.ToTable("Reservaciones");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("AM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaNa")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.HabitacionReservada", b =>
                {
                    b.HasOne("PIA_MAD.Modelos.Habitaciones", "Habitacion")
                        .WithMany()
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PIA_MAD.Modelos.Reservacion", "Reservacion")
                        .WithMany("HabitacionesReservadas")
                        .HasForeignKey("ReservacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Habitacion");

                    b.Navigation("Reservacion");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.Habitaciones", b =>
                {
                    b.HasOne("PIA_MAD.Modelos.Hoteles", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.Reservacion", b =>
                {
                    b.HasOne("PIA_MAD.Modelos.Usuario", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PIA_MAD.Modelos.Hoteles", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PIA_MAD.Modelos.ReporteVentas", null)
                        .WithMany("reservaciones")
                        .HasForeignKey("ReporteVentasid");

                    b.Navigation("Cliente");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.ReporteVentas", b =>
                {
                    b.Navigation("reservaciones");
                });

            modelBuilder.Entity("PIA_MAD.Modelos.Reservacion", b =>
                {
                    b.Navigation("HabitacionesReservadas");
                });
#pragma warning restore 612, 618
        }
    }
}
